name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: ["2.7", "3.8"]
    runs-on: python:${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Install requirements (py ${{ matrix.python-version }})
      run: |
        pip install -e ".[testing]"
    - name: Run all tests (py ${{ matrix.python-version }})
      run: python -m unittest discover
