name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: ["2.7", "3.8"]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        pip install -e ".[testing]"
    - name: Run all tests
      run: python -m unittest discover
